services:
  base-image:
    image: wireguard-base
    build: base
    deploy:
      replicas: 0
    cap_add:
      - ALL

  server:
    build: server
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    depends_on:
      - base-image
    networks:
      - wg_net

  client:
    build: client
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    depends_on:
      - base-image
      - server
    networks:
      - wg_net

networks:
  wg_net:
